const data = {
    envType: [
        {
            id: 1,
            envName: "INDOOR",
        },
        {
            id: 2,
            envName: "OUTDOOR",
        }
    ]
    ,
    roomType: [
        {
            id: 1,
            roomTheme: "Standard Room",
            image: "/assets/RoomThemes/1.png"
        },
        {
            id: 2,
            image: "/assets/RoomThemes/2.png",
            roomTheme: "TV Studio",

        }
        , {
            id: 3,
            image: "/assets/RoomThemes/3.png",
            roomTheme: "Meeting Room",

        },
        {
            id: 4,
            image: "/assets/RoomThemes/4.png",
            roomTheme: "Control Room",

        },
        {
            id: 5,
            image: "/assets/RoomThemes/5.png",
            roomTheme: "Lobby",

        }
    ],
    configurationData: [
        {
            "id": 1,
            "category": "INDOOR",
            "description": "Fine Pitch LED Display - GOB",
            "model": "COMET-G 0.9",
            "pixelPitch": "0.93",
            "ledType": "Mini 4-in-1 GOB",
            "brightness": "600",
        },
        {
            "id": 2,
            "category": "INDOOR",
            "description": "Fine Pitch LED Display - GOB", "brightness": "800",
        },
        {
            "id": 5,
            "category": "INDOOR",
            "description": "Fine Pitch LED Display - GOB",
            "model": "COMET-G 2.0",
            "pixelPitch": "2.3",
            "ledType": "SMD 3-in-1 GOB",
            "brightness": "800",

        },
        {
            "id": 6,
            "category": "INDOOR",
            "description": "Fine Pitch LED Display - COB",
            "model": "COMET-C 0.7",
            "pixelPitch": "0.79",
            "ledType": "Flip Chip COB",
            "brightness": "600",

        },
        {
            "id": 7,
            "category": "INDOOR",
            "description": "Fine Pitch LED Display - COB",
            "model": "COMET-C 0.9",
            "pixelPitch": "0.95",
            "ledType": "Flip Chip COB",
            "brightness": "800",

        },
        {
            "id": 8,
            "category": "INDOOR",
            "description": "Fine Pitch LED Display - COB",
            "model": "COMET-C 1.2",
            "pixelPitch": "1.27",
            "ledType": "Flip Chip COB",
            "brightness": "800",

        },
        {
            "id": 9,
            "category": "INDOOR",
            "description": "Fine Pitch LED Display - COB",
            "model": "COMET-C 1.5",
            "pixelPitch": "1.58",
            "ledType": "Flip Chip COB",
            "brightness": "800",

        },
        {
            "id": 10,
            "category": "INDOOR",
            "description": "Fine Pitch LED Display - COB",
            "model": "COMET-C 1.9",
            "pixelPitch": "1.9",
            "ledType": "Flip Chip COB",
            "brightness": "800",

        },
        {
            "id": 11,
            "category": "INDOOR",
            "description": "Fine Pitch LED Display - COB V",
            "model": "COMET-CV 0.4",
            "pixelPitch": "0.47",
            "ledType": "Flip Chip COB",
            "brightness": "600",

        },
        {
            "id": 12,
            "category": "INDOOR",
            "description": "Fine Pitch LED Display - COB V",
            "model": "COMET-CV 0.6",
            "pixelPitch": "0.63",
            "ledType": "Flip Chip COB",
            "brightness": "800",

        },
        {
            "id": 13,
            "category": "INDOOR",
            "description": "Fine Pitch LED Display - COB V",
            "model": "COMET-CV 0.7",
            "pixelPitch": "0.79",
            "ledType": "Flip Chip COB",
            "brightness": "800",

        },
        {
            "id": 14,
            "category": "INDOOR",
            "description": "Fine Pitch LED Display - COB V",
            "model": "COMET-CV 0.9",
            "pixelPitch": "0.95",
            "ledType": "Flip Chip COB",
            "brightness": "800",

        },
        {
            "id": 15,
            "category": "INDOOR",
            "description": "Fine Pitch LED Display - COB V",
            "model": "COMET-CV 1.2",
            "pixelPitch": "1.19",
            "ledType": "Flip Chip COB",
            "brightness": "800",

        },
        {
            "id": 16,
            "category": "INDOOR",
            "description": "Fine Pitch LED Display - SMD",
            "model": "COMET-E 1.2",
            "pixelPitch": "1.25",
            "ledType": "SMD 3-in-1",
            "brightness": "600",

        },
        {
            "id": 17,
            "category": "INDOOR",
            "description": "Fine Pitch LED Display - SMD",
            "model": "COMET-E 1.5",
            "pixelPitch": "1.56",
            "ledType": "SMD 3-in-1",
            "brightness": "600",

        },
        {
            "id": 18,
            "category": "INDOOR",
            "description": "Fine Pitch LED Display - SMD",
            "model": "COMET-E 1.8",
            "pixelPitch": "1.88",
            "ledType": "SMD 3-in-1",
            "brightness": "600",

        },
        {
            "id": 19,
            "category": "INDOOR",
            "description": "Fine Pitch LED Display - SMD",
            "model": "COMET-E 2.5",
            "pixelPitch": "2.5",
            "ledType": "SMD 3-in-1",
            "brightness": "600",

        },
        {
            "id": 20,
            "category": "INDOOR",
            "description": "Indoor High-Resolution 16:9 LED Display",
            "model": "PLUTO-1.5",
            "pixelPitch": "1.56",
            "ledType": "SMD 3-in-1 GOB",
            "brightness": "1000",

        },
        {
            "id": 21,
            "category": "INDOOR",
            "description": "Indoor High-Resolution 16:9 LED Display",
            "model": "PLUTO-1.8",
            "pixelPitch": "1.86",
            "ledType": "SMD 3-in-1 GOB",
            "brightness": "1000",

        },
        {
            "id": 22,
            "category": "INDOOR",
            "description": "Indoor High-Resolution 16:9 LED Display",
            "model": "PLUTO-2.5",
            "pixelPitch": "2.5",
            "ledType": "SMD 3-in-1 GOB",
            "brightness": "800",

        },
        {
            "id": 23,
            "category": "INDOOR",
            "description": "Creative Smart Module LED Display",
            "model": "MBOX-1.5",
            "pixelPitch": "1.56",
            "ledType": "SMD 3-in-1 GOB",
            "brightness": "600",

        },
        {
            "id": 24,
            "category": "INDOOR",
            "description": "Creative Smart Module LED Display",
            "model": "MBOX-1.8",
            "pixelPitch": "1.81",
            "ledType": "SMD 3-in-1 GOB",
            "brightness": "600",

        },
        {
            "id": 25,
            "category": "INDOOR",
            "description": "Creative Smart Module LED Display",
            "model": "MBOX-2.5",
            "pixelPitch": "2.5",
            "ledType": "SMD 3-in-1 GOB",
            "brightness": "600",

        },
        {
            "id": 26,
            "category": "INDOOR",
            "description": "Creative Flexible LED Display",
            "model": "URANUS-1.9",
            "pixelPitch": "1.95",
            "ledType": "SMD 3-in-1",
            "brightness": "800",

        },
        {
            "id": 27,
            "category": "INDOOR",
            "description": "Creative Flexible LED Display",
            "model": "URANUS-2.6",
            "pixelPitch": "2.6",
            "ledType": "SMD 3-in-1",
            "brightness": "800",

        },
        {
            "id": 28,
            "category": "INDOOR",
            "description": "Creative Flexible LED Display",
            "model": "URANUS-3.1",
            "pixelPitch": "3.1",
            "ledType": "SMD 3-in-1",
            "brightness": "800",

        },
        {
            "id": 29,
            "category": "INDOOR",
            "description": "Creative Flexible LED Display",
            "model": "URANUS-3.9",
            "pixelPitch": "3.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800",

        },
        {
            "id": 30,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE 1.5 | 500 x 250",
            "pixelPitch": "1.56",
            "ledType": "SMD 3-in-1",
            "brightness": "600",

        },
        {
            "id": 31,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-1.9 | 500x1000",
            "pixelPitch": "1.95",
            "ledType": "SMD 3-in-1",
            "brightness": "600",

        },
        {
            "id": 32,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-1.9 | 500x750",
            "pixelPitch": "1.95",
            "ledType": "SMD 3-in-1",
            "brightness": "600",

        },
        {
            "id": 33,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-1.9 | 500x500",
            "pixelPitch": "1.95",
            "ledType": "SMD 3-in-1",
            "brightness": "600",

        },
        {
            "id": 34,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-1.9 | 500x250",
            "pixelPitch": "1.95",
            "ledType": "SMD 3-in-1",
            "brightness": "600",

        },
        {
            "id": 35,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-1.9 | 250x500",
            "pixelPitch": "1.95",
            "ledType": "SMD 3-in-1",
            "brightness": "600",

        },
        {
            "id": 36,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-1.9 | 250x750",
            "pixelPitch": "1.95",
            "ledType": "SMD 3-in-1",
            "brightness": "600",

        },
        {
            "id": 37,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-1.9 | 250x1000",
            "pixelPitch": "1.95",
            "ledType": "SMD 3-in-1",
            "brightness": "600",

        },
        {
            "id": 38,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-1.9 | 750x250",
            "pixelPitch": "1.95",
            "ledType": "SMD 3-in-1",
            "brightness": "600",

        },
        {
            "id": 39,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-1.9 | 1000x250",
            "pixelPitch": "1.95",
            "ledType": "SMD 3-in-1",
            "brightness": "600",

        },
        {
            "id": 40,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.5 | 500x1000",
            "pixelPitch": "2.5",
            "ledType": "SMD 3-in-1",
            "brightness": "800",

        },
        {
            "id": 41,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.5 | 500x750",
            "pixelPitch": "2.5",
            "ledType": "SMD 3-in-1",
            "brightness": "800",

        },
        {
            "id": 42,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.5 | 500x500",
            "pixelPitch": "2.5",
            "ledType": "SMD 3-in-1",
            "brightness": "800",

        },
        {
            "id": 43,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.5 | 500x250",
            "pixelPitch": "2.5",
            "ledType": "SMD 3-in-1",
            "brightness": "800",

        },
        {
            "id": 44,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.5 | 250x500",
            "pixelPitch": "2.5",
            "ledType": "SMD 3-in-1",
            "brightness": "800",
        },
        {
            "id": 45,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.5 | 250x750",
            "pixelPitch": "2.5",
            "ledType": "SMD 3-in-1",
            "brightness": "800",
        },
        {
            "id": 46,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.5 | 250x1000",
            "pixelPitch": "2.5",
            "ledType": "SMD 3-in-1",
            "brightness": "800",

        },
        {
            "id": 47,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.5 | 1000x250",
            "pixelPitch": "2.5",
            "ledType": "SMD 3-in-1",
            "brightness": "800",

        },
        {
            "id": 48,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.5 | 750x250",
            "pixelPitch": "2.5",
            "ledType": "SMD 3-in-1",
            "brightness": "800",

        },
        {
            "id": 49,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.6 | 500x1000",
            "pixelPitch": "2.6",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",

        },
        {
            "id": 50,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.6 | 500x750",
            "pixelPitch": "2.6",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",

        },
        {
            "id": 51,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.6 | 500x500",
            "pixelPitch": "2.6",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",

        },
        {
            "id": 52,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.6 | 500x250",
            "pixelPitch": "2.6",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",

        },
        {
            "id": 53,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.6 | 250x500",
            "pixelPitch": "2.6",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",

        },
        {
            "id": 54,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.6 | 250x750",
            "pixelPitch": "2.6",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",

        },
        {
            "id": 55,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.6 | 250x1000",
            "pixelPitch": "2.6",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",

        },
        {
            "id": 56,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.6 | 1000x250",
            "pixelPitch": "2.6",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",
        },
        {
            "id": 57,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.6 | 750x250",
            "pixelPitch": "2.6",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",
        },
        {
            "id": 58,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.9 | 500x1000",
            "pixelPitch": "2.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",


        },
        {
            "id": 59,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.9 | 500x750",
            "pixelPitch": "2.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",
        },
        {
            "id": 60,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.9 | 500x500",
            "pixelPitch": "2.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",
        },
        {
            "id": 61,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.9 | 500x250",
            "pixelPitch": "2.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",
        },
        {
            "id": 62,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.9 | 250x500",
            "pixelPitch": "2.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",
        },
        {
            "id": 63,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.9 | 250x750",
            "pixelPitch": "2.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",
        },
        {
            "id": 64,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.9 | 250x1000",
            "pixelPitch": "2.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",

        },
        {
            "id": 65,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.9 | 1000x250",
            "pixelPitch": "2.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",
        },
        {
            "id": 66,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-2.9 | 750x250",
            "pixelPitch": "2.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",
        },
        {
            "id": 67,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-3.1 | 500x1000",
            "pixelPitch": "3.1",
            "ledType": "SMD 3-in-1",
            "brightness": "800",


        },
        {
            "id": 68,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-3.1 | 500x750",
            "pixelPitch": "3.1",
            "ledType": "SMD 3-in-1",
            "brightness": "800",
        },
        {
            "id": 69,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-3.1 | 500x500",
            "pixelPitch": "3.1",
            "ledType": "SMD 3-in-1",
            "brightness": "800",
        },
        {
            "id": 70,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-3.1 | 500x250",
            "pixelPitch": "3.1",
            "ledType": "SMD 3-in-1",
            "brightness": "800",
        },
        {
            "id": 71,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-3.1 | 250x500",
            "pixelPitch": "3.1",
            "ledType": "SMD 3-in-1",
            "brightness": "800",
        },
        {
            "id": 72,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-3.1 | 250x750",
            "pixelPitch": "3.1",
            "ledType": "SMD 3-in-1",
            "brightness": "800",
        },
        {
            "id": 73,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-3.1 | 250x1000",
            "pixelPitch": "3.1",
            "ledType": "SMD 3-in-1",
            "brightness": "800",

        },
        {
            "id": 74,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-3.1 | 1000x250",
            "pixelPitch": "3.1",
            "ledType": "SMD 3-in-1",
            "brightness": "800",
        },
        {
            "id": 75,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-3.1 | 750x250",
            "pixelPitch": "3.1",
            "ledType": "SMD 3-in-1",
            "brightness": "800",
        },
        {
            "id": 76,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-3.9 | 500x1000",
            "pixelPitch": "3.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",


        },
        {
            "id": 77,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-3.9 | 500x750",
            "pixelPitch": "3.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",
        },
        {
            "id": 78,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-3.9 | 500x500",
            "pixelPitch": "3.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",
        },
        {
            "id": 79,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-3.9 | 500x250",
            "pixelPitch": "3.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",
        },
        {
            "id": 80,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-3.9 | 250x500",
            "pixelPitch": "3.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",
        },
        {
            "id": 81,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-3.9 | 250x750",
            "pixelPitch": "3.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",
        },
        {
            "id": 82,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-3.9 | 250x1000",
            "pixelPitch": "3.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",

        },
        {
            "id": 83,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-3.9 | 1000x250",
            "pixelPitch": "3.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",
        },
        {
            "id": 84,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-3.9 | 750x250",
            "pixelPitch": "3.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800 / 3000",
        },
        {
            "id": 85,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-4.8 | 500x1000",
            "pixelPitch": "4.8",
            "ledType": "SMD 3-in-1",
            "brightness": "800",


        },
        {
            "id": 86,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-4.8 | 500x750",
            "pixelPitch": "4.8",
            "ledType": "SMD 3-in-1",
            "brightness": "800",
        },
        {
            "id": 87,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-4.8 | 500x500",
            "pixelPitch": "4.8",
            "ledType": "SMD 3-in-1",
            "brightness": "800",
        },
        {
            "id": 88,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-4.8 | 500x250",
            "pixelPitch": "4.8",
            "ledType": "SMD 3-in-1",
            "brightness": "800",
        },
        {
            "id": 89,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-4.8 | 250x500",
            "pixelPitch": "4.8",
            "ledType": "SMD 3-in-1",
            "brightness": "800",
        },
        {
            "id": 90,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-4.8 | 250x750",
            "pixelPitch": "4.8",
            "ledType": "SMD 3-in-1",
            "brightness": "800",
        },
        {
            "id": 91,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-4.8 | 250x1000",
            "pixelPitch": "4.8",
            "ledType": "SMD 3-in-1",
            "brightness": "800",

        },
        {
            "id": 92,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-4.8 | 1000x250",
            "pixelPitch": "4.8",
            "ledType": "SMD 3-in-1",
            "brightness": "800",
        },
        {
            "id": 93,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-4.8 | 750x250",
            "pixelPitch": "4.8",
            "ledType": "SMD 3-in-1",
            "brightness": "800",
        },
        {
            "id": 94,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-5.9 | 500x1000",
            "pixelPitch": "5.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800",

        },
        {
            "id": 95,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-5.9 | 500x750",
            "pixelPitch": "5.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800",
        },
        {
            "id": 96,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-5.9 | 500x500",
            "pixelPitch": "5.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800",
        },
        {
            "id": 97,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-5.9 | 500x250",
            "pixelPitch": "5.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800",
        },
        {
            "id": 98,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-5.9 | 250x500",
            "pixelPitch": "5.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800",
        },
        {
            "id": 99,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-5.9 | 250x750",
            "pixelPitch": "5.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800",
        },
        {
            "id": 100,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-5.9 | 250x1000",
            "pixelPitch": "5.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800",

        },
        {
            "id": 101,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-5.9 | 1000x250",
            "pixelPitch": "5.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800",
        },
        {
            "id": 102,
            "category": "INDOOR",
            "description": "Fixed Installation LED Display",
            "model": "NEPTUNE-5.9 | 750x250",
            "pixelPitch": "5.9",
            "ledType": "SMD 3-in-1",
            "brightness": "800",
        },
        {
            "id": 103,
            "category": "INDOOR",
            "description": "Floor LED Display",
            "model": "JUPITER-2.6",
            "pixelPitch": "2.6",
            "ledType": "SMD 3-in-1",
            "brightness": "800",
        },
        {
            "id": 104,
            "category": "INDOOR",
            "description": "Floor LED Display",
            "model": "JUPITER-2.9",
            "pixelPitch": "2.9",
            "ledType": "SMD 3-in-1",
            "brightness": "2600",
        },
        {
            "id": 105,
            "category": "INDOOR",
            "description": "Floor LED Display",
            "model": "JUPITER-3.9",
            "pixelPitch": "3.9",
            "ledType": "SMD 3-in-1",
            "brightness": "2600",
        },
        {
            "id": 106,
            "category": "INDOOR",
            "description": "Floor LED Display",
            "model": "JUPITER-5.2",
            "pixelPitch": "5.2",
            "ledType": "SMD 3-in-1",
            "brightness": "3000",
        },
        {
            "id": 107,
            "category": "INDOOR",
            "description": "Floor LED Display",
            "model": "JUPITER-6.2",
            "pixelPitch": "6.2",
            "ledType": "SMD 3-in-1",
            "brightness": "3000",
        },
        {
            "id": 108,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-1.9 | 500X500",
            "pixelPitch": "1.95",
            "ledType": "SMD 3-in-1",
            "brightness": "3500",
        },
        {
            "id": 109,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-2.5 | 640x640",
            "pixelPitch": "2.5",
            "ledType": "SMD 3-in-1",
            "brightness": "5000",
        },
        {
            "id": 110,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-2.9 | 500x500",
            "pixelPitch": "2.97",
            "ledType": "SMD 3-in-1",
            "brightness": "2500 ~ 4500",
        },
        {
            "id": 111,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-2.9 | 500x750",
            "pixelPitch": "2.97",
            "ledType": "SMD 3-in-1",
            "brightness": "2500 ~ 4500",
        },
        {
            "id": 112,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-3.9 | 500x500",
            "pixelPitch": "3.91",
            "ledType": "SMD 3-in-1",
            "brightness": "4500 ~ 7000",
        },
        {
            "id": 113,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-3.9 | 500x750",
            "pixelPitch": "3.91",
            "ledType": "SMD 3-in-1",
            "brightness": "4500 ~ 7000",
        },
        {
            "id": 114,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-3.9 | 500x1000",
            "pixelPitch": "3.91",
            "ledType": "SMD 3-in-1",
            "brightness": "4500 ~ 7000",

        },
        {
            "id": 115,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-4.8 | 500x500",
            "pixelPitch": "4.81",
            "ledType": "SMD 3-in-1",
            "brightness": "4500 ~ 7000",
        },
        {
            "id": 116,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-4.8 | 500x750",
            "pixelPitch": "4.81",
            "ledType": "SMD 3-in-1",
            "brightness": "4500 ~ 7000",
        },
        {
            "id": 117,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-4.8 | 500x1000",
            "pixelPitch": "4.81",
            "ledType": "SMD 3-in-1",
            "brightness": "4500 ~ 7000",

        },
        {
            "id": 118,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-5.7 | 960x640",
            "pixelPitch": "5.71",
            "ledType": "SMD 3-in-1",
            "brightness": "6000 ~ 8000",
        },
        {
            "id": 119,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-5.7 | 960x960",
            "pixelPitch": "5.71",
            "ledType": "SMD 3-in-1",
            "brightness": "6000 ~ 8000",
        },
        {
            "id": 120,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-5.7 | 960x1280",
            "pixelPitch": "5.71",
            "ledType": "SMD 3-in-1",
            "brightness": "6000 ~ 8000",

        },
        {
            "id": 121,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-5.7 | 1440x640",
            "pixelPitch": "5.71",
            "ledType": "SMD 3-in-1",
            "brightness": "6000 ~ 8000",
        },
        {
            "id": 122,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-5.7 | 1440x960",
            "pixelPitch": "5.71",
            "ledType": "SMD 3-in-1",
            "brightness": "6000 ~ 8000",
        },
        {
            "id": 123,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-5.7 | 1440x1280",
            "pixelPitch": "5.71",
            "ledType": "SMD 3-in-1",
            "brightness": "6000 ~ 8000",

        },
        {
            "id": 124,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-6.6 | 960x640",
            "pixelPitch": "6.6",
            "ledType": "SMD 3-in-1",
            "brightness": "5500 ~ 8500",
        },
        {
            "id": 125,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-6.6 | 960x960",
            "pixelPitch": "6.6",
            "ledType": "SMD 3-in-1",
            "brightness": "5500 ~ 8500",
        },
        {
            "id": 126,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-6.6 | 960x1280",
            "pixelPitch": "6.6",
            "ledType": "SMD 3-in-1",
            "brightness": "5500 ~ 8500",

        },
        {
            "id": 127,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-6.6 | 1440x640",
            "pixelPitch": "6.6",
            "ledType": "SMD 3-in-1",
            "brightness": "5500 ~ 8500",
        },
        {
            "id": 128,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-6.6 | 1440x960",
            "pixelPitch": "6.6",
            "ledType": "SMD 3-in-1",
            "brightness": "5500 ~ 8500",
        },
        {
            "id": 129,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-6.6 | 1440x1280",
            "pixelPitch": "6.6",
            "ledType": "SMD 3-in-1",
            "brightness": "5500 ~ 8500",

        },
        {
            "id": 130,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-8 | 960x640",
            "pixelPitch": "8",
            "ledType": "SMD 3-in-1",
            "brightness": "6000 ~ 10000",
        },
        {
            "id": 131,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-8 | 960x960",
            "pixelPitch": "8",
            "ledType": "SMD 3-in-1",
            "brightness": "6000 ~ 10000",
        },
        {
            "id": 132,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-8 | 960x1280",
            "pixelPitch": "8",
            "ledType": "SMD 3-in-1",
            "brightness": "6000 ~ 10000",

        },
        {
            "id": 133,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-8 | 1440x640",
            "pixelPitch": "8",
            "ledType": "SMD 3-in-1",
            "brightness": "6000 ~ 10000",
        },
        {
            "id": 134,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-8 | 1440x960",
            "pixelPitch": "8",
            "ledType": "SMD 3-in-1",
            "brightness": "6000 ~ 10000",
        },
        {
            "id": 135,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-8 | 1440x1280",
            "pixelPitch": "8",
            "ledType": "SMD 3-in-1",
            "brightness": "6000 ~ 10000",

        },
        {
            "id": 136,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-10 | 960x640",
            "pixelPitch": "10",
            "ledType": "SMD 3-in-1",
            "brightness": "6000 ~ 10000",
        },
        {
            "id": 137,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-10 | 960x960",
            "pixelPitch": "10",
            "ledType": "SMD 3-in-1",
            "brightness": "6000 ~ 10000",
        },
        {
            "id": 138,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-10 | 960x1280",
            "pixelPitch": "10",
            "ledType": "SMD 3-in-1",
            "brightness": "6000 ~ 10000",

        },
        {
            "id": 139,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-10 | 1440x640",
            "pixelPitch": "10",
            "ledType": "SMD 3-in-1",
            "brightness": "6000 ~ 10000",
        },
        {
            "id": 140,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-10 | 1440x960",
            "pixelPitch": "10",
            "ledType": "SMD 3-in-1",
            "brightness": "6000 ~ 10000",
        },
        {
            "id": 141,
            "category": "OUTDOOR",
            "description": "Fixed Installation LED Display",
            "model": "MERCURY-10 | 1440x1280",
            "pixelPitch": "10",
            "ledType": "SMD 3-in-1",
            "brightness": "6000 ~ 10000",

        },
        {
            "id": 147,
            "category": "INDOOR",
            "description": "Transparent LED Nebula 3.9-3.9",
            "model": "Nebula 3.9-3.9",
            "pixelPitch": "3.91",
            "ledType": "SMD 3in1",
            "brightness": "3500",
        },
    ]
}

export default data;